#!/usr/bin/env python3
"""Regenerate include/yui/gfx/koi_art.hpp from assets/koi.brl.

Run from repo root:
    python3 scripts/gen_koi_art.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "koi.brl"
DST = ROOT / "include" / "yui" / "gfx" / "koi_art.hpp"


def main() -> None:
    text = SRC.read_text(encoding="utf-8").rstrip("\n")
    lines = text.split("\n")
    rows = len(lines)
    cols = len(lines[0]) if lines else 0
    assert all(len(line) == cols for line in lines), "ragged koi.brl"

    body = "\n".join(
        '    "{esc}\\n"'.format(
            esc="".join(f"\\x{b:02x}" for b in line.encode("utf-8"))
        )
        for line in lines
    )

    hpp = f"""#pragma once
// Yui koi splash art — UTF-8 Unicode Braille, {cols} chars × {rows} lines
// ({cols * 2}×{rows * 4} dots).
// Source: assets/koi.brl. Generated by scripts/gen_koi_art.py — do not hand-edit.

namespace yui {{

inline constexpr const char* kKoiArt =
{body};

constexpr int kKoiArtCols  = {cols};
constexpr int kKoiArtRows  = {rows};
constexpr int kKoiArtDotsW = kKoiArtCols * 2;  // {cols * 2}
constexpr int kKoiArtDotsH = kKoiArtRows * 4;  // {rows * 4}

}}  // namespace yui
"""
    DST.write_text(hpp, encoding="utf-8")
    print(f"wrote {DST.relative_to(ROOT)} ({rows} rows × {cols} cols)")


if __name__ == "__main__":
    main()
