#!/usr/bin/env python3
"""Convert raw artwork into C++ headers with PROGMEM byte arrays.

Inputs (relative to the project root):
  art/boot/frame_NN.png       → include/yui/assets/boot_frames.hpp
  art/sprites/<name>_sheet.png → include/yui/assets/sprite_<name>.hpp

Each output header exposes the PNG bytes + length + sprite metadata so
the firmware can call drawPng(bytes, len, x, y) directly.

Run after dropping new artwork in art/. Idempotent.
"""

import argparse
from pathlib import Path
import re
import sys
import textwrap


def emit_byte_array(name: str, data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    body = "\n".join(rows)
    return (f"inline const uint8_t {name}[] PROGMEM = {{\n"
            f"{body}\n"
            f"}};\n"
            f"inline constexpr std::size_t {name}_len = {len(data)};\n")


def gen_boot_frames(repo: Path) -> None:
    src_dir = repo / "art" / "boot"
    out = repo / "include" / "yui" / "assets" / "boot_frames.hpp"
    out.parent.mkdir(parents=True, exist_ok=True)

    frames = sorted(src_dir.glob("frame_*.png"))
    if not frames:
        print(f"[assets] no boot frames in {src_dir} — skipping")
        return

    parts = [
        "#pragma once",
        "// Auto-generated by tools/gen_assets.py — DO NOT EDIT.",
        "// Source artwork: art/boot/frame_*.png",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "#if defined(YUI_TARGET_CARDPUTER_ADV)",
        "#include <pgmspace.h>",
        "#else",
        "#define PROGMEM",
        "#endif",
        "",
        "namespace yui::assets {",
        "",
    ]

    for f in frames:
        idx = re.search(r"frame_(\d+)", f.name).group(1)
        data = f.read_bytes()
        parts.append(emit_byte_array(f"boot_frame_{idx}", data))

    parts.append(f"inline constexpr std::size_t kBootFrameCount = {len(frames)};")
    parts.append("")
    parts.append("struct BootFrameRef {")
    parts.append("  const uint8_t* data;")
    parts.append("  std::size_t    len;")
    parts.append("};")
    parts.append("")
    parts.append("inline constexpr BootFrameRef kBootFrames[kBootFrameCount] = {")
    for f in frames:
        idx = re.search(r"frame_(\d+)", f.name).group(1)
        parts.append(f"  {{ boot_frame_{idx}, boot_frame_{idx}_len }},")
    parts.append("};")
    parts.append("")
    parts.append("}  // namespace yui::assets")
    parts.append("")

    out.write_text("\n".join(parts))
    total = sum(f.stat().st_size for f in frames)
    print(f"[assets] {out.relative_to(repo)} — {len(frames)} frames, "
          f"{total} bytes ({total/1024:.1f} KB)")


def gen_sprite_sheets(repo: Path) -> None:
    src_dir = repo / "art" / "sprites"
    out_dir = repo / "include" / "yui" / "assets"
    out_dir.mkdir(parents=True, exist_ok=True)

    if not src_dir.exists():
        return

    from PIL import Image

    written = []
    for png in sorted(src_dir.glob("*_sheet.png")):
        name_match = re.match(r"(.+)_(\d+)x(\d+)_sheet\.png", png.name)
        if not name_match:
            print(f"[assets] skipping {png.name} (expected name_WxH_sheet.png)")
            continue
        slug, fw, fh = name_match.group(1), int(name_match.group(2)), int(name_match.group(3))
        data = png.read_bytes()
        with Image.open(png) as img:
            sheet_w, sheet_h = img.size
        n = sheet_w // fw
        if sheet_w % fw or sheet_h != fh:
            print(f"[assets] {png.name} dims {sheet_w}x{sheet_h} not a "
                  f"clean {fw}x{fh} strip — using best-effort frame count {n}")

        c_slug = re.sub(r"[^A-Za-z0-9]", "_", slug)
        out = out_dir / f"sprite_{c_slug}.hpp"

        body = [
            "#pragma once",
            "// Auto-generated by tools/gen_assets.py — DO NOT EDIT.",
            f"// Source: art/sprites/{png.name} ({sheet_w}x{sheet_h}, "
            f"frame {fw}x{fh}, {n} frames)",
            "",
            "#include <cstddef>",
            "#include <cstdint>",
            "",
            "#if defined(YUI_TARGET_CARDPUTER_ADV)",
            "#include <pgmspace.h>",
            "#else",
            "#define PROGMEM",
            "#endif",
            "",
            "namespace yui::assets {",
            "",
            emit_byte_array(f"sprite_{c_slug}_png", data),
            f"inline constexpr int sprite_{c_slug}_frame_w  = {fw};",
            f"inline constexpr int sprite_{c_slug}_frame_h  = {fh};",
            f"inline constexpr int sprite_{c_slug}_count    = {n};",
            f"inline constexpr int sprite_{c_slug}_sheet_w  = {sheet_w};",
            f"inline constexpr int sprite_{c_slug}_sheet_h  = {sheet_h};",
            "",
            "}  // namespace yui::assets",
            "",
        ]
        out.write_text("\n".join(body))
        written.append((png.name, len(data)))
        print(f"[assets] {out.relative_to(repo)} — {len(data)} bytes "
              f"({n} frames at {fw}x{fh})")

    return written


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=Path(__file__).resolve().parent.parent)
    args = ap.parse_args()
    repo = Path(args.repo)
    gen_boot_frames(repo)
    gen_sprite_sheets(repo)


if __name__ == "__main__":
    main()
