#!/usr/bin/env python3
"""Convert raw artwork into C++ headers with PROGMEM byte arrays.

Inputs (relative to the project root):
  art/boot/frame_NN.png       → include/yui/assets/boot_frames.hpp
  art/sprites/<name>_sheet.png → include/yui/assets/sprite_<name>.hpp

Each output header exposes the PNG bytes + length + sprite metadata so
the firmware can call drawPng(bytes, len, x, y) directly.

Run after dropping new artwork in art/. Idempotent.
"""

import argparse
from pathlib import Path
import re
import sys
import textwrap


def emit_byte_array(name: str, data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    body = "\n".join(rows)
    return (f"inline const uint8_t {name}[] PROGMEM = {{\n"
            f"{body}\n"
            f"}};\n"
            f"inline constexpr std::size_t {name}_len = {len(data)};\n")


def gen_boot_frames(repo: Path) -> None:
    src_dir = repo / "art" / "boot"
    out = repo / "include" / "yui" / "assets" / "boot_frames.hpp"
    out.parent.mkdir(parents=True, exist_ok=True)

    frames = sorted(src_dir.glob("frame_*.png"))
    if not frames:
        print(f"[assets] no boot frames in {src_dir} — skipping")
        return

    parts = [
        "#pragma once",
        "// Auto-generated by tools/gen_assets.py — DO NOT EDIT.",
        "// Source artwork: art/boot/frame_*.png",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "#if defined(YUI_TARGET_CARDPUTER_ADV)",
        "#include <pgmspace.h>",
        "#else",
        "#define PROGMEM",
        "#endif",
        "",
        "namespace yui::assets {",
        "",
    ]

    for f in frames:
        idx = re.search(r"frame_(\d+)", f.name).group(1)
        data = f.read_bytes()
        parts.append(emit_byte_array(f"boot_frame_{idx}", data))

    parts.append(f"inline constexpr std::size_t kBootFrameCount = {len(frames)};")
    parts.append("")
    parts.append("struct BootFrameRef {")
    parts.append("  const uint8_t* data;")
    parts.append("  std::size_t    len;")
    parts.append("};")
    parts.append("")
    parts.append("inline constexpr BootFrameRef kBootFrames[kBootFrameCount] = {")
    for f in frames:
        idx = re.search(r"frame_(\d+)", f.name).group(1)
        parts.append(f"  {{ boot_frame_{idx}, boot_frame_{idx}_len }},")
    parts.append("};")
    parts.append("")
    parts.append("}  // namespace yui::assets")
    parts.append("")

    out.write_text("\n".join(parts))
    total = sum(f.stat().st_size for f in frames)
    print(f"[assets] {out.relative_to(repo)} — {len(frames)} frames, "
          f"{total} bytes ({total/1024:.1f} KB)")


def gen_sprite_sheets(repo: Path) -> None:
    src_dir = repo / "art" / "sprites"
    out_dir = repo / "include" / "yui" / "assets"
    out_dir.mkdir(parents=True, exist_ok=True)

    if not src_dir.exists():
        return

    from PIL import Image

    written = []
    for png in sorted(src_dir.glob("*_sheet.png")):
        name_match = re.match(r"(.+)_(\d+)x(\d+)_sheet\.png", png.name)
        if not name_match:
            print(f"[assets] skipping {png.name} (expected name_WxH_sheet.png)")
            continue
        slug, fw, fh = name_match.group(1), int(name_match.group(2)), int(name_match.group(3))
        data = png.read_bytes()
        with Image.open(png) as img:
            sheet_w, sheet_h = img.size
        n = sheet_w // fw
        if sheet_w % fw or sheet_h != fh:
            print(f"[assets] {png.name} dims {sheet_w}x{sheet_h} not a "
                  f"clean {fw}x{fh} strip — using best-effort frame count {n}")

        c_slug = re.sub(r"[^A-Za-z0-9]", "_", slug)
        out = out_dir / f"sprite_{c_slug}.hpp"

        # Slice the sheet into per-frame PNGs and emit each as its own
        # PROGMEM byte array. This lets the firmware call draw_png(frame)
        # to render a single frame, instead of having to crop the sheet at
        # runtime (which would mean keeping a decoded sprite resident).
        import io
        with Image.open(png) as img_full:
            img = img_full.convert("RGB")
            frame_blobs = []
            for k in range(n):
                box = (k * fw, 0, (k + 1) * fw, fh)
                frame = img.crop(box)
                buf = io.BytesIO()
                # Quantize to a small palette so per-frame PNGs stay compact;
                # source artwork is already palettized so this is lossless
                # in practice.
                frame.quantize(colors=64, method=Image.MEDIANCUT,
                               dither=Image.FLOYDSTEINBERG).save(
                    buf, format="PNG", optimize=True)
                frame_blobs.append(buf.getvalue())

        body = [
            "#pragma once",
            "// Auto-generated by tools/gen_assets.py — DO NOT EDIT.",
            f"// Source: art/sprites/{png.name} ({sheet_w}x{sheet_h}, "
            f"frame {fw}x{fh}, {n} frames)",
            "",
            "#include <cstddef>",
            "#include <cstdint>",
            "",
            "#if defined(YUI_TARGET_CARDPUTER_ADV)",
            "#include <pgmspace.h>",
            "#else",
            "#define PROGMEM",
            "#endif",
            "",
            "#include \"yui/assets/sprite_frame.hpp\"",
            "",
            "namespace yui::assets {",
            "",
        ]

        for k, blob in enumerate(frame_blobs):
            body.append(emit_byte_array(f"sprite_{c_slug}_f{k:02d}", blob))

        body += [
            f"inline constexpr int sprite_{c_slug}_frame_w  = {fw};",
            f"inline constexpr int sprite_{c_slug}_frame_h  = {fh};",
            f"inline constexpr int sprite_{c_slug}_count    = {n};",
            "",
            f"inline constexpr SpriteFrame sprite_{c_slug}_frames[{n}] = {{",
        ]
        for k in range(n):
            body.append(
                f"  {{ sprite_{c_slug}_f{k:02d}, sprite_{c_slug}_f{k:02d}_len }},"
            )
        body += [
            "};",
            "",
            "}  // namespace yui::assets",
            "",
        ]
        out.write_text("\n".join(body))
        written.append((png.name, len(data)))
        print(f"[assets] {out.relative_to(repo)} — {len(data)} bytes "
              f"({n} frames at {fw}x{fh})")

    return written


def gen_icons(repo: Path) -> None:
    """Embed art/icons/*.png as PROGMEM byte arrays + an IconId enum.

    Each PNG is identified by its filename stem (e.g. `menu1_r2c1`) and
    exposed as `kIcon_<stem>` (data + len). A single `IconRef` array
    indexes them so apps can pick by enum or by raw stem.
    """
    src_dir = repo / "art" / "icons"
    out = repo / "include" / "yui" / "assets" / "icons.hpp"
    out.parent.mkdir(parents=True, exist_ok=True)

    pngs = sorted(p for p in src_dir.glob("*.png") if not p.name.startswith("_"))
    if not pngs:
        print(f"[icons] no PNGs in {src_dir} — skipping header gen")
        return

    parts = [
        "#pragma once",
        "// Auto-generated by tools/gen_assets.py — DO NOT EDIT.",
        "// Source artwork: art/icons/*.png (sliced from menu1/menu2 sheets).",
        "//",
        "// Each entry is a PNG blob suitable for IDisplay::draw_png. The",
        "// IconId enum lets apps reference icons symbolically; semantic",
        "// aliases (kIcon_Radio, kIcon_WiFi, ...) live below the raw set.",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "#if defined(YUI_TARGET_CARDPUTER_ADV)",
        "#include <pgmspace.h>",
        "#else",
        "#define PROGMEM",
        "#endif",
        "",
        "namespace yui::assets {",
        "",
        "struct IconRef {",
        "  const uint8_t* data;",
        "  std::size_t    len;",
        "  int            size;   // square px",
        "};",
        "",
    ]

    refs = []
    total_bytes = 0
    icon_size = 48  # must match tools/extract_icons.py default
    for p in pngs:
        stem = p.stem
        ident = "icon_" + stem.replace("-", "_")
        data = p.read_bytes()
        total_bytes += len(data)
        parts.append(emit_byte_array(ident, data))
        refs.append((stem, ident))

    parts.append(f"inline constexpr int kIconSize = {icon_size};")
    parts.append("")
    parts.append("// Stem-keyed table (ordered as the source files were).")
    parts.append(f"inline constexpr IconRef kIcons[{len(refs)}] = {{")
    for stem, ident in refs:
        parts.append(f"  {{ {ident}, {ident}_len, kIconSize }},  // {stem}")
    parts.append("};")
    parts.append(f"inline constexpr std::size_t kIconCount = {len(refs)};")
    parts.append("")

    # Stem → index lookup (linear; we only have ~32 icons).
    parts.append("inline constexpr int icon_index_by_stem(const char* s) {")
    parts.append("  if (!s) return -1;")
    for i, (stem, _ident) in enumerate(refs):
        parts.append(f"  if (__builtin_strcmp(s, \"{stem}\") == 0) return {i};")
    parts.append("  return -1;")
    parts.append("}")
    parts.append("")

    # Semantic aliases — Phase 2 mapping. Each maps a Launcher/Chrome
    # role to one of the source icons. Renaming a slot here changes the
    # whole firmware in one place.
    aliases = {
        # Top-level launcher categories
        "Radio":     "menu1_r2c4",   # cloud-waves — broadcast feel
        "WiFi":      "menu1_r1c4",   # folded fan — radiating arcs
        "Bluetooth": "menu2_r4c2",   # mitsudomoe spiral — connectivity
        "Tools":     "menu1_r4c2",   # diamond lattice — utility/grid
        "System":    "menu1_r2c1",   # torii — gateway / system
        "Fun":       "menu1_r4c3",   # koi — playful
        # Reusable submenu / action icons
        "Scan":      "menu1_r3c2",   # yin-yang — scanning balance
        "Capture":   "menu1_r3c1",   # paper crane — capture
        "Replay":    "menu2_r2c4",   # alt torii — re-entry
        "Jam":       "menu2_r2c3",   # rising sun + clouds — interference
        "Brute":     "menu1_r4c1",   # kimono/haori — armored
        "Spoof":     "menu2_r3c2",   # alt fan — disguise
        "Inject":    "menu2_r4c3",   # bowl chopsticks — pointed
        "Files":     "menu2_r1c2",   # lantern — light browsing
        "Settings":  "menu1_r3c3",   # teapot — adjust
        "Info":      "menu1_r1c1",   # flag/circle — emblem
        "Mascot":    "menu1_r4c3",   # koi
    }
    parts.append("// Semantic aliases — the Phase 2 mapping. Roles → source icons.")
    parts.append("// Renaming a slot here changes the whole firmware in one place.")
    parts.append("namespace icons {")
    for alias, stem in aliases.items():
        parts.append(f"inline const IconRef& k{alias}() {{")
        parts.append(f"  // {stem}")
        parts.append(f"  return kIcons[icon_index_by_stem(\"{stem}\")];")
        parts.append("}")
    parts.append("}  // namespace icons")
    parts.append("")
    parts.append("}  // namespace yui::assets")
    parts.append("")

    out.write_text("\n".join(parts))
    print(f"[icons] {out.relative_to(repo)} — {len(refs)} icons, "
          f"{total_bytes} bytes ({total_bytes/1024:.1f} KB)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=Path(__file__).resolve().parent.parent)
    args = ap.parse_args()
    repo = Path(args.repo)
    gen_boot_frames(repo)
    gen_sprite_sheets(repo)
    gen_icons(repo)


if __name__ == "__main__":
    main()
